# Generated by Django 4.0.5 on 2022-07-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Instructor',
            new_name='instructor',
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.ManyToManyField(to='courses.tag'),
        ),
    ]
