# Generated by Django 4.0.5 on 2022-07-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_tag_rename_instructor_course_instructor_category_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tag',
            new_name='tags',
        ),
    ]
