# Generated by Django 4.0.5 on 2022-07-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_tag_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='courses.tag'),
        ),
    ]
